// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA14N14TrW5Rrkq-iOV3QbZYeeq_PiP2bw',
    appId: '1:599109006425:web:23a390a05220505ede2d48',
    messagingSenderId: '599109006425',
    projectId: 'hw04-619d4',
    authDomain: 'hw04-619d4.firebaseapp.com',
    storageBucket: 'hw04-619d4.firebasestorage.app',
    measurementId: 'G-GRQCEXTGDF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDW-MquKxRNjmZp4VLphWMGh6fw9cdBQ-Y',
    appId: '1:599109006425:android:5571e63d2e021b1fde2d48',
    messagingSenderId: '599109006425',
    projectId: 'hw04-619d4',
    storageBucket: 'hw04-619d4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4-eEk-MHNRxvBd-n6lYU-xLgivtF0Ga4',
    appId: '1:599109006425:ios:785b95d8fe411d64de2d48',
    messagingSenderId: '599109006425',
    projectId: 'hw04-619d4',
    storageBucket: 'hw04-619d4.firebasestorage.app',
    iosBundleId: 'com.example.hw4Messageboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4-eEk-MHNRxvBd-n6lYU-xLgivtF0Ga4',
    appId: '1:599109006425:ios:785b95d8fe411d64de2d48',
    messagingSenderId: '599109006425',
    projectId: 'hw04-619d4',
    storageBucket: 'hw04-619d4.firebasestorage.app',
    iosBundleId: 'com.example.hw4Messageboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA14N14TrW5Rrkq-iOV3QbZYeeq_PiP2bw',
    appId: '1:599109006425:web:f29e04507ae1cb06de2d48',
    messagingSenderId: '599109006425',
    projectId: 'hw04-619d4',
    authDomain: 'hw04-619d4.firebaseapp.com',
    storageBucket: 'hw04-619d4.firebasestorage.app',
    measurementId: 'G-508FDE3EK3',
  );
}
